hide_submit.settings:
  type: mapping
  label: Settings
  mapping:
    hide_submit_method:
      type: string
    hide_submit_reset_time:
      type: integer
    hide_submit_abtext:
      type: string
    hide_submit_atext:
      type: string
    hide_submit_hide_fx:
      type: boolean
    hide_submit_hide_text:
      type: string
    hide_submit_indicator_style:
      type: string
    hide_submit_spinner_color:
      type: string
    hide_submit_spinner_lines:
      type: integer
    hide_submit_status:
      type: boolean
    hide_submit_css:
      type: string
    hide_submit_hide_css:
      type: string
